name: Update Recent GitHub Activity

on:
  schedule:
    # Run daily at 01:00 UTC (06:30 IST)
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Sync Recent Public Activity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Recent GitHub Activity Section
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "chore(profile): update recent GitHub activity [skip ci]"
          MAX_LINES: 5
